--- #YAML:1.0
name:                SourceCode-LineCounter-Perl
version:             0.10_02
abstract:            This is what the module does
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
    Test::Output:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
